stages:
  - pull
  - deploy

job_pull:
  stage: pull
  script:
    - echo "Pulling latest"
    - git checkout AddAvatars
    - git pull

job_deploy:
  stage: deploy
  script:
    - echo "Running tests"
    - cd Frontend
    - npm i
    - cd ..
    - cd Backend
    - npm i
    - cd ..
    - cd Frontend
    - npm run build
    - cd ~/scribble
